capture_lenght_minutes: 1
chessboard_cols: 4
chessboard_rows: 18
experiment_name: VSB_July_03
exposuretime: 2.328
framerate: 400
height: 100
pixel_to_mm_ratio: 0.41
pixelclock: 160
root_directory: D:\Hella
sqr_size_mm: 6
width: 800
hardware_gain: 50
hardware_gamma: 100